#!/bin/bash

# run from /path/to/programming-language-thing
cd ..

# use nodemon to do the magic
nodemon \
  --ignore workspace_built.js \
  --exec browserify workspace/workspace.js -o workspace/workspace_built.js
